openlibraryenvironment/mod-rs

service/grails-app/services/org/olf/rs/ReshareApplicationEventHandlerService.groovy

PR to refactor and neaten code that creates `PatronRequestNotifications` with notes

Cleaned up code checking for notes in iso18626 messages

---

service/grails-app/services/org/olf/rs/ReshareActionService.groovy
service/src/main/okapi/tenant/sample_data/_data.groovy

Added a chat setting to allow for messages to be marked as read automatically, or not (or in special cases)
Added bulk mark as read action
Added logic to deal with special cases, on or off.

Chat settings

---

service/grails-app/controllers/mod/rs/PatronRequestController.groovy
service/grails-app/domain/PatronRequestLoanCondition.groovy
service/grails-app/domain/org/olf/rs/PatronRequest.groovy
service/grails-app/domain/org/olf/rs/PatronRequestNotification.groovy
service/grails-app/migrations/initial-model.groovy
service/grails-app/services/org/olf/rs/HousekeepingService.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageBuildingService.groovy
service/grails-app/services/org/olf/rs/ReshareActionService.groovy
service/grails-app/services/org/olf/rs/ReshareApplicationEventHandlerService.groovy
service/grails-app/views/patronRequest/_patronRequest.gson
service/grails-app/views/patronRequestLoanCondition/_patronRequestLoanCondition.gson
service/src/main/okapi/tenant/sample_data/_data.groovy

This PR adds several actions and states pertaining to the ability to send request responses containing conditions, and handling that workflow

Loan conditions and cancelling requests

---

service/build.gradle
service/grails-app/migrations/initial-model.groovy

Upgraded to dm-directory 1.1.17

Directory dependency upgrade

---

service/grails-app/controllers/mod/rs/NoticePolicyController.groovy
service/grails-app/controllers/mod/rs/UrlMappings.groovy
service/grails-app/domain/org/olf/rs/NoticePolicy.groovy
service/grails-app/domain/org/olf/rs/NoticePolicyNotice.groovy
service/grails-app/migrations/initial-model.groovy
service/grails-app/views/noticePolicy/_noticePolicy.gson
service/grails-app/views/noticePolicyNotice/_noticePolicyNotice.gson
service/src/main/okapi/ModuleDescriptor-template.json

Will add refdata columns for trigger and format when implementing those.

Initial notice policies endpoint and domain model

---

service/grails-app/services/org/olf/rs/WmsHostLMSService.groovy
service/src/main/okapi/tenant/sample_data/_data.groovy

Changed ncip api/secret to be wms specific, reflected that in code. Also moved loan to borrow ratio into shared properties

Bootstrapped data changes

---

service/grails-app/services/org/olf/rs/ReshareApplicationEventHandlerService.groovy

Refactored parton validation block to ensure requesting institution d…ata ends up on the request regardless

PR-1019: Request is sent without requester if the patron lookup initially fails

---

service/grails-app/domain/org/olf/rs/statemodel/Status.groovy
service/grails-app/migrations/module-tenant-changelog.groovy
service/grails-app/migrations/update-mod-rs-2-4.groovy
service/grails-app/services/org/olf/rs/HousekeepingService.groovy

Added a boolean to Status object which indicates whether a state is terminal or not
PR-1126

feat: Status 'terminal' boolean

---

service/grails-app/controllers/mod/rs/PatronRequestController.groovy

Cancellation is now possible before a supplier has been identified for a request. The request simply transitions directly to state "CANCELLED" without ISO18626 conversation.
PR-1120

feat: Cancellation of New request

---

service/grails-app/services/org/olf/rs/DirectoryEntryService.groovy
service/grails-app/services/org/olf/rs/routing/FoliosharedindexRouterService.groovy
service/grails-app/services/org/olf/rs/routing/StaticRouterService.groovy

Refactored request routing code to use shared service, takes into account directory entry loan policy (provided foaf has been walked since it changed).
Refs PR-687

fix: Refactor and fix

---

service/grails-app/domain/org/olf/rs/PatronRequest.groovy

Tweaks to title truncation, added logging and truncation also for numerous other fields
PR-1029

fix: Validation

---

service/grails-app/services/org/olf/rs/statemodel/actions/ActionPatronRequestPatronReturnedItemAndShippedReturnService.groovy
service/grails-app/services/org/olf/rs/statemodel/actions/ActionResponderSupplierCheckInToReshareAndSupplierMarkShippedService.groovy
service/src/main/groovy/org/olf/rs/referenceData/AvailableActionData.groovy
service/src/main/groovy/org/olf/rs/referenceData/Settings.groovy
service/src/main/groovy/org/olf/rs/statemodel/Actions.groovy

Added new actions available which combine:
- CheckIntoReShare and Ship on the supplier side
- Mark retured by patron and Mark return shipped on the requester side

PR-1017/PR-1020: Combined actions

---

okapi-scripts/testOpenURL.sh
service/grails-app/services/org/olf/rs/HostLMSLocationService.groovy
service/grails-app/services/org/olf/rs/HostLMSPatronProfileService.groovy
service/grails-app/services/org/olf/rs/HostLMSShelvingLocationService.groovy

…KeyException if the key exists in a different object, so we no longer attach

Attaching an object to the current session, may result in a Duplicate… 

---

okapi-scripts/run_rancher_desktop.sh
okapi-scripts/secure_enable.sh
okapi-scripts/secure_register.sh

3 scripts added - allowing mod-rs to be registered and enabled to a tenant (rancher-desktop).

rancher-desktop scripts added

---

service/grails-app/conf/application-rancher-desktop.yml

Issue fixed: defaults to port 8080
Fix: Added a config file which can be specified in grade,properties

helps mod-rs run port 8081 (rancher-desktop)

---

service/grails-app/migrations/update-mod-rs-2-12.groovy
service/grails-app/services/org/olf/rs/BatchService.groovy

PR-1421 We nos also flag a batch as whether it belongs to a requester…..

---

.github/workflows/gradle.yml
.github/workflows/release.yml

updates workflow for building release branch, tags.

Release test 2.14.x

---

service/grails-app/services/org/olf/rs/hostlms/PolarisHostLMSService.groovy

* Fix protocol version from 2 to 1.

PR-1563 - Create a Host LMS adapter for Polaris.

---

service/grails-app/domain/org/olf/rs/statemodel/ActionEventResultList.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventRespNewPatronRequestIndService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventRespNewSlnpPatronRequestIndService.groovy
service/src/integration-test/groovy/org/olf/SLNPStateModelSpec.groovy
service/src/main/groovy/org/olf/rs/referenceData/RefdataValueData.groovy
service/src/main/groovy/org/olf/rs/referenceData/SLNPStateModelData.groovy
service/src/main/groovy/org/olf/rs/referenceData/SettingsData.groovy

Double check with Kurt why do we an answer from host LMS.

PR-1710 - extend the auto-responder with support for NCIP RequestItem.

---

service/grails-app/domain/org/olf/rs/PatronRequest.groovy
service/grails-app/migrations/update-mod-rs-2-19.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageBuildingService.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventMessageRequestIndService.groovy
service/grails-app/views/patronRequest/_patronRequest.gson
service/src/integration-test/groovy/org/olf/RSLifecycleSpec.groovy
service/src/main/groovy/org/olf/rs/referenceData/RefdataValueData.groovy

Add fields needed for PR-2055 and PR-2057 (ServiceLevel and MaximumCost).
Only a subset of possible currencycodes are currently implemented.

Initial addition of fields and migrations

---

service/build.gradle
service/grails-app/services/org/olf/rs/DirectoryEntryService.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageBuildingService.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageService.groovy
service/grails-app/services/org/olf/rs/ReshareApplicationEventHandlerService.groovy
service/grails-app/services/org/olf/rs/routing/FoliosharedindexRouterService.groovy
service/grails-app/services/org/olf/rs/routing/StaticRouterService.groovy
service/grails-app/services/org/olf/rs/statemodel/actions/iso18626/ActionISO18626RequesterService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventISO18626IncomingAbstractService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventMessageRequestIndService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventNonreturnableRequesterNewPatronRequestIndService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventReqNewPatronRequestIndService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventReqNewSlnpPatronRequestIndService.groovy
service/grails-app/services/org/olf/rs/statemodel/events/EventSendToNextLenderService.groovy
service/src/integration-test/groovy/org/olf/SLNPStateModelSpec.groovy
service/src/test/groovy/org/olf/rs/DirectoryEntryServiceSpec.groovy

Also eliminate duplication of resolveSymbol/resolveCombinedSymbol

Allow colons in symbols PR-2068

---

service/grails-app/services/org/olf/rs/hostlms/HorizonHostLMSService.groovy
service/src/test/groovy/org/olf/rs/hostlms/HorizonHostLMSServiceSpec.groovy
service/src/test/resources/zresponsexml/horizon-hennepin.xml
service/src/test/resources/zresponsexml/horizon-southeastern.xml

Modify Horizon Host LMS Item Location logic (#744)

---

okapi-scripts/register_and_enable.sh
okapi-scripts/submit_local_patron_request.sh
service/grails-app/conf/application.yml
service/grails-app/conf/logback.xml
service/grails-app/controllers/mod/rs/SettingController.groovy
service/src/integration-test/groovy/org/olf/AppSettingSpec.groovy
service/src/integration-test/groovy/org/olf/TestBase.groovy
service/src/main/okapi/DeploymentDescriptor-template.json
service/src/main/okapi/ModuleDescriptor-template.json

*sigh* accidentally included some local-only changes.

Revert "Per-section perms to GET settings ILLDEV-41"

---

service/grails-app/services/org/olf/rs/ProtocolMessageBuildingService.groovy
service/grails-app/services/org/olf/rs/ProtocolMessageService.groovy
service/grails-app/services/org/olf/rs/statemodel/actions/iso18626/ActionPatronRequestISO18626StatusChangeService.groovy
service/src/integration-test/groovy/org/olf/RSLifecycleSpec.groovy

Enable parsing of returnInfo physical address for supplier side

Enable parsing of returnInfo physical address for supplier side
